(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const l=document.querySelectorAll(".navigation-item");l.forEach(n=>{n.addEventListener("click",function(o){o.preventDefault(),l.forEach(c=>c.classList.remove("active")),this.classList.add("active")})});document.addEventListener("DOMContentLoaded",function(){const n=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),c=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(n.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),n.style.display="none"}),c.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),n.style.display="none"})});document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll('a[href^="#"]').forEach(n=>{n.addEventListener("click",function(o){o.preventDefault();const c=this.getAttribute("href").substring(1),r=document.getElementById(c);if(r){const t=r.offsetTop-90;window.scrollTo({top:t,behavior:"smooth"})}})})});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),o=n.querySelector(".icon"),c=document.querySelector(".modal"),r=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const s=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#FFD811" />
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#F6F6F6" stroke-linecap="round" />
</svg>
    `,d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#FFD811" />
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#F6F6F6" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;n.addEventListener("click",()=>{t=!t,o.innerHTML=t?d:s,t?a():i()}),r.forEach(f=>f.addEventListener("click",()=>{i(),o.innerHTML=s,t=!1})),window.addEventListener("scroll",u);function a(){c.style.display="block"}function i(){c.style.display="none"}function u(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});
//# sourceMappingURL=index.js.map
